---
name: actionlint
on: [ pull_request ]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: actionlint
        uses: reviewdog/action-actionlint@v1
