---
name: Assign
on: [ pull_request ]

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      -
        name: Assign @nasa9084
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee @nasa9084
