---
name: depup
on:
  schedule:
    - cron: "34 1 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps:
          - version_name: terraform_version
            repo: hashicorp/terraform
          - version_name: TFCMT_VERSION
            repo: suzuki-shunsuke/tfcmt
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: reviewdog/action-depup/with-pr@v1
        with:
          github_token: ${{ secrets.GH_PAT }}
          file: .github/workflows/terraform-plan.yml
          version_name: ${{ matrix.apps.version_name }}
          repo: ${{ matrix.apps.repo }}
  apply:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps:
          - version_name: terraform_version
            repo: hashicorp/terraform
          - version_name: TFCMT_VERSION
            repo: suzuki-shunsuke/tfcmt
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: reviewdog/action-depup/with-pr@v1
        with:
          github_token: ${{ secrets.GH_PAT }}
          file: .github/workflows/terraform-apply.yml
          version_name: ${{ matrix.apps.version_name }}
          repo: ${{ matrix.apps.repo }}
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps:
          - version_name: terraform_version
            repo: hashicorp/terraform
          - version_name: tflint_version
            repo: terraform-linters/tflint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: reviewdog/action-depup/with-pr@v1
        with:
          github_token: ${{ secrets.GH_PAT }}
          file: .github/workflows/lint.yml
          version_name: ${{ matrix.apps.version_name }}
          repo: ${{ matrix.apps.repo }}
          # terraform has includes alpha/beta/rc pre-releases
          # tfcmt has pre-release suffixed by -N
          exclude: (-(alpha|beta|rc))|(-[0-9]+$)
