---
name: depup
on:
  schedule:
    - cron: "34 1 * * *"
  workflow_dispatch:

jobs:
  depup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files:
          - .github/workflows/terraform-plan.yml
          - .github/workflows/terraform-apply.yml
          - .github/workflows/lint.yml
        apps:
          - version_name: terraform_version
            repo: hashicorp/terraform
          - version_name: TFCMT_VERSION
            repo: suzuki-shunsuke/tfcmt
          - version_name: tflint_version
            repo: terraform-linters/tflint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: reviewdog/action-depup/with-pr@v1
        with:
          file: .github/workflows/${{ matrix.files }}
          version_name: ${{ matrix.apps.version_name }}
          repo: ${{ matrix.apps.repo }}
