---
name: Terraform Apply
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  changed:
    if: github.event.pull_request.merged == true
    name: Detect changed directories
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.changed-terraform-directories.outputs.all_changed_files }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      -
        name: Get changed subdirs
        uses: tj-actions/changed-files@v45
        id: changed-terraform-directories
        with:
          dir_names: true
          json: true
          escape_json: false
          files: |
            **.tf
      -
        name: List all changed terraform directories
        run: echo '${{ steps.changed-terraform-directories.outputs.all_changed_files }}'
  apply:
    name: Terraform Apply
    if: needs.changed.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    needs: [ changed ]
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        target: ${{ fromJSON(needs.changed.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.3
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      -
        name: Setup tfcmt
        env:
          TFCMT_VERSION: v4.14.2
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar -xf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin
          tfcmt --version
      -
        name: Terraform init
        run: terraform -chdir=${{ matrix.target }} init
      -
        name: Terraform apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt -var "target:${{ matrix.target }}" apply -- terraform -chdir=${{ matrix.target }} apply -auto-approve
